apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
data:
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  PaymentSimulation__ForcedStatus: ""
  ASPNETCORE_URLS: "http://+:8080"
